### ISSUE TITLE
Uso externo de las impresoras

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/actas#61]
Esta issue nace de https://github.com/asrob-uc3m/impresoras-asrob/issues/15# (@kleiren cc @Siotma) como foro para debatir sobre la política de uso de las impresoras. Una vez decididos los parámetros variables, se podría establecer una votación de enmienda en https://github.com/asrob-uc3m/estatutos

Lo único que está claro es:
`Al ser una impresora del Departamento (DISA) y otra nuestra, y el espacio del DISA, nos piden que dejemos que se utilicen para cosas del DISA.`

Variables:
- Uso para otros Departamentos.
- Uso para externos a la Universidad.
- Determinar un coste. P.ej. en fungibles/filamento por unidad de tiempo/producto.
- Sobre todo en el caso de no poner un coste, determinar un límite superior de tiempo/producto.

¿Más ideas/varaibles?

**Comment by Siotma** [comment]
Esto debería resucitarse, de cara a este año convendría tenerlo aclarado. Desde mi opinión también está claro que la Asociación mantiene las impresoras y debería tener derecho pleno de uso gratuito.

En mi opinión el uso de las impresoras ha sido históricamente gratuito, aunque monetizarlo podría ser una fuente de ingresos para la asociación, al final probablemente los intereses de distintas partes nos darán muchos más quebraderos de cabeza que beneficios. Digo esto pensando en que:
- El Departamento podrá reclamar parte de los beneficios como suyos
- Quizá tener beneficios como asociación pueda traernos obligaciones extra con la Universidad
- Al poner precio a las impresoras, se pueden generar situaciones de picaresca poco recomendables

Quizá se puede poner, por ejemplo, un umbral de horas de uso al mes a partir del cual haya que pagar, confiando yo creo en que nadie lo sobrepasará. Si el tiempo nos dice que puede merecer la pena, o que es necesario subir el precio por una demanda excesiva, se podrá volver a plantear.

**Comment by JorFru** [comment]
¿Cuándo se habló sobre monetizar el asunto?
Alguna tarde de cerves? Porque yo no me enteré

Gracias

On Oct 9, 2017 02:08, "Manu" <notifications@github.com> wrote:

Esto debería resucitarse, de cara a este año convendría tenerlo aclarado.
Desde mi opinión también está claro que la Asociación mantiene las
impresoras y debería tener derecho pleno de uso gratuito.

En mi opinión el uso de las impresoras ha sido históricamente gratuito,
aunque monetizarlo podría ser una fuente de ingresos para la asociación, al
final probablemente los intereses de distintas partes nos darán muchos más
quebraderos de cabeza que beneficios. Digo esto pensando en que:

   - El Departamento podrá reclamar parte de los beneficios como suyos
   - Quizá tener beneficios como asociación pueda traernos obligaciones
   extra con la Universidad
   - Al poner precio a las impresoras, se pueden generar situaciones de
   picaresca poco recomendables

Quizá se puede poner, por ejemplo, un umbral de horas de uso al mes a
partir del cual haya que pagar, confiando yo creo en que nadie lo
sobrepasará. Si el tiempo nos dice que puede merecer la pena, o que es
necesario subir el precio por una demanda excesiva, se podrá volver a
plantear.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/actas/issues/61#issuecomment-335048566>, or mute
the thread

**Comment by jgvictores** [comment]
> ¿Cuándo se habló sobre monetizar el asunto?

Nos lo han llegado a ofrecer.

> un umbral de horas de uso al mes a partir del cual haya que pagar, confiando yo creo en que nadie lo sobrepasará.

El problema es que se podría llegar a sobrepasar, en cuyo caso volveríamos a la misma duda. Esto es, veo estas posibilidades:

1. Se podría establecer un umbral tope y punto.
2. Se podría estipular un coste por tiempo de uso y que el pago fuese en material (plástico por poco uso, componentes/mejoras por mucho uso).
3. El modelo intermedio propuesto por @Siotma que obliga a que de todas formas se estipule (2).

¿Qué tal si partimos de (1) como solución temporal más sencilla? ¿De qué orden de magnitud de umbral hablaríamos?

**Comment by Siotma** [comment]
Partiendo de esta base:

> Desde mi opinión también está claro que la Asociación mantiene las impresoras y debería tener derecho pleno de uso gratuito.

Yo creo que el uso por parte de la comunidad universitaria debería ser libre por el mismo motivo hasta que se produzcan problemas de exceso de demanda. Para gente que venga de fuera de la universidad, se entiende que el uso sería esporádico, por lo que se puede establecer un límite de, por ejemplo, 5 horas.

Sería interesante conocer los modelos de uso que tienen entidades tipo makerspace / fablab o similares para coger ideas.

**Comment by David-Estevez** [comment]
También hay que tener en cuenta que con su uso por parte de terceros las impresoras supondrán más gastos, tanto de material como de mantenimiento( ya que habrá partes que acaben rompiéndose) y habría que pensar quién se haría cargo de esos gastos. En la actualidad el encargado de esos gastos es el departamento, pero si los gastos empiezan a crecer, puede que ellos dejen de costearlos.

Por otro lado, también debería quedar claro que el hecho de ser externos a la Asociación (Departamento o miembros de la comunidad  universitaria) no exime de tener que realizar la formación para usar la impresora.

> Sería interesante conocer los modelos de uso que tienen entidades tipo makerspace / fablab o similares para coger ideas.

Los modelos más típicos que conozco son dos: una cuota mensual de miembro que permite el acceso a las distintas máquinas y/o el cobro por material (medido en masa o volumen) de la pieza a imprimir.

**Comment by Siotma** [comment]
> Por otro lado, también debería quedar claro que el hecho de ser externos a la Asociación (Departamento o miembros de la comunidad universitaria) no exime de tener que realizar la formación para usar la impresora.

Por supuesto.

> Los modelos más típicos que conozco son dos: una cuota mensual de miembro que permite el acceso a las distintas máquinas y/o el cobro por material (medido en masa o volumen) de la pieza a imprimir.

Yo siempre he pensado que el cobro por material es el más justo. En mi opinión lo óptimo es un precio algo superior al precio de coste (por ejemplo, el doble) en concepto de material y desgaste de la máquina, para realizar reparaciones con los beneficios.

**Comment by David-Estevez** [comment]
Yo estaría a favor de ese cobro por material y coste de mantenimiento, ya que no me parece que haya lucro detrás de él, sino un interés por hacer de este préstamo de uso algo mantenible en el tiempo.

**Comment by Siotma** [comment]
Yo también estoy a favor. Según he leído, y enlazando con #93 , algunos gestores de impresoras en la nube tienen auto implementada la funcionalidad de estimación de precios por impresión...

**Comment by JorFru** [comment]
Necesitamos que las impresoras estén automatizadas para que esto sea viable.
