### ISSUE TITLE
Darnos de baja en el IEEE

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/actas#89]
Dado que no participamos en ninguna de las actividades del IEEE, en la reunión del 14/09/17 se decidió abandonar la IEEE Student Branch.

**Comment by David-Estevez** [comment]
@KFRodicio nos informa de que ha iniciado las conversaciones para darnos de baja en el IEEE.

**Comment by jgvictores** [comment]
@KFRodicio ¿Falta algo por hacer aquí?

**Comment by David-Estevez** [comment]
¿Alguna novedad, @KFRodicio ?

**Comment by KFRodicio** [comment]
Estuve hablando con la que lleva el tema y me dijo que se pondría en
contacto conmigo

El 11 abr. 2018 11:30 p. m., "David Estévez Fernández" <
notifications@github.com> escribió:

¿Alguna novedad, @KFRodicio <https://github.com/KFRodicio> ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/actas/issues/89#issuecomment-380601897>, or mute
the thread

**Comment by KFRodicio** [comment]
Si no me dicen nada en breves, le volveré a escribir

**Comment by jgvictores** [comment]
No tengo nada claro por escrito, pero RoboticsLab quieren hacer algo IEEE Student Branch Chapter para IROS2018, que es en octubre. No sé en qué se traduce esto a efectos prácticos (ni teóricos :sweat_smile:).

Iré tratando de averiguar qué quieren exactamente, y como siempre esforzándome que esto tenga las mínimas repercusiones posibles.

**Comment by David-Estevez** [comment]
Dado que no aparecemos aquí: https://www.ieeespain.org/grupos/ramas-estudiantes/ voy a suponer que ya no somos rama activa del IEEE y que se puede cerrar esta issue.
